# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-08 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deckard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='deckard.Post'),
            preserve_default=False,
        ),
    ]
