# Generated by Django 2.0 on 2017-12-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deckard', '0002_blogpost_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post_id',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_likes', to='deckard.Comment', verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_likes', to='deckard.Post', verbose_name='post'),
        ),
    ]
