# Generated by Django 2.0 on 2018-01-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckard', '0002_auto_20171220_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hidden',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected'), ('HD', 'Hidden')], default='Pending', max_length=50, verbose_name='status'),
        ),
    ]
