# Generated by Django 2.0 on 2017-12-07 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deckard', '0002_auto_20171206_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposted_blogposts', to=settings.AUTH_USER_MODEL, verbose_name='publisher'),
        ),
    ]
