# Generated by Django 2.0 on 2017-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckard', '0002_auto_20171205_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
