# Generated by Django 2.0 on 2017-12-11 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckard', '0002_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[-1], size=None),
        ),
    ]
