# Generated by Django 2.0 on 2017-12-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckard', '0003_post_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='publication date'),
        ),
    ]
