# Generated by Django 2.0 on 2018-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckard', '0004_auto_20180113_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('PN', 'В ожидании'), ('AP', 'Одобрен'), ('RJ', 'Отклонён'), ('HD', 'Скрыт')], default='Pending', max_length=50, verbose_name='status'),
        ),
    ]
