"""
Django settings for cain project.

Generated by 'django-admin startproject' using Django 1.10.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEBUG = os.environ.get('DKRD_DEBUG', 'off') == 'on'
TEMPLATE_DEBUG = DEBUG
SECRET_KEY = os.environ.get('DKRD_SECRET_KEY', os.urandom(32))
ALLOWED_HOSTS = ["." + host for host in os.environ.get('DKRD_ALLOWED_HOSTS', 'localhost').split(',')]

# For reversing urls
SITE_DOMAIN = os.environ.get('DKRD_SITE_DOMAIN', "localhost")
SITE_PREFIX = os.environ.get('DKRD_SITE_PREFIX', "http://")

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'deckard',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.vk',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'deckard.middleware.UserIsContributorMiddleware',
    'deckard.middleware.HostToBlogNameMiddleware',
]

ROOT_URLCONF = 'cain.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": [
            os.path.join(BASE_DIR, 'deckard/templates/jinja2'),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "deckard.jinja2.environment",
            'context_processors': [
                'deckard.context_processors.custom_context',
            ]
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'deckard/templates/allauth'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',

            ],
        },
    },
]

WSGI_APPLICATION = 'cain.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static"),
#]

STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGIN_REDIRECT_URL = "/blog/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/blog/"

SESSION_COOKIE_DOMAIN = '.' + SITE_DOMAIN.split(":", 1)[0]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DKRD_DB_NAME', "postgres"),
        'USER': os.environ.get('DKRD_DB_USER', "postgres"),
        'PASSWORD': os.environ.get('DKRD_DB_PASSWORD', ""),
        'HOST': os.environ.get('DKRD_DB_HOST', "db"),
        'PORT': os.environ.get('DKRD_DB_PORT', "5432"),
    }
}

#from .local_settings import *

# local_settings.py:
# SECRET_KEY = 'some_secret_sequence_of_symbols'
# DATABASES = {...}
# ALLOWED_HOSTS = [...]
# DEBUG = TRUE (or False)
